### ISSUE TITLE
Follow up ticket for v3 release

### ISSUE THREAD

**Issue by jptosso** [corazawaf/coraza#336]
This issue is meant to keep track of V3 alpha release issues

CC @fzipi @piyushroshan @anuraaga @bxlxx @jcchavezs 

## Tasks

- [x] Variable engine rework (90%)
  -  pending key case fix by @piyushroshan 
- [x] API refactor (90%)
  - Pending moving a few functions to internal and validating if we keep tx context
  - Moving tx metadata to types
- [x] Response body processor (50%)
  - Pieces are programmed, but there are some pending tests and connections
- [x] Refactor core interfaces for plugins (90%)
  - Some other types must be moved to types
- [x] 100% CRS compatibility
- [ ] Implement custom dynamic variables (TIME, ENV, etc): 0%
- [x] Tinygo and WASM compatibility
- [x] Remove zap and create logging interface
- [x] Performance optimization
- [x] Create benchmarks between v2 and v3
- [x] Rework the rule error log mechanism
- [x] Expose Directive plugins api
- [ ] #810
- [ ] Add more tests for rule exceptions (example: Wordpress exceptions for CRS)

## High-Level breaking changes

- `waf.NewTransaction` now receives a Context
- `seclang.NewParser` will stop returning an error
- `tx.Collections` now returns Collection objects. Raw data is not available anymore. Variables can be retrieved from `tx.Variables.RemoteAddr`

## Milestone dates (Expected)

- **09/09/2022:** Tag v3.0.0-alpha.1
- **09/09/2022:** Add repository rules to v3/dev: 1 approver
- **09/09/2022:** Replace v2/master with v3/dev as the default branch
- **14/10/2022:** Tag v3.0.0-rc.1
- **14/10/2022:** Add repository rules to v3/dev: 2 approvers
- **14/10/2022:** Rename the v3/dev branch to v3/main and v2/master to v2/main
- **18/11/2022:** v3.0.0 stable release

**Comment by anuraaga** [comment]
If we go with current API, I think the proposed schedule makes sense. But if decide to go with #371, it will be a big change, and we may lump in other similar API changes at this chance. So if going with it, I believe we need 1 extra month, but no more. That would push back e.g., `v3.0.0-alpha.1` to `07/10/2002`.  If not, let's stick to simple renames and the proposed schedule.

**Comment by sts** [comment]
Preparing a Changelog for v3 https://github.com/corazawaf/coraza/pull/538

**Comment by fzipi** [comment]
Do we know what is needed for the body processors mentioned here?

**Comment by hex-m** [comment]
This issue is linked on the very top of the [website](https://coraza.io/). This does not look good. Please reopen and give a status update or stop linking to this.

**Comment by jcchavezs** [comment]
Closed as v3 is out.
